WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET VERIFY OFF

ALTER SESSION SET CONTAINER = FREEPDB1;

ACCEPT app_password CHAR PROMPT 'Enter password for ETL_LAB: ' HIDE
CREATE USER ETL_LAB IDENTIFIED BY "&app_password";
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO ETL_LAB;
ALTER USER ETL_LAB QUOTA 100M ON USERS;

UNDEFINE app_password
PROMPT ETL_LAB application user created with minimum schema privileges.
EXIT SUCCESS
