const S={map:null,curation:null,nodes:new Map(),generated:[],view:null,selected:null,trail:[],camera:{x:0,y:0,w:1200,h:760},drag:null};
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function init(){try{const [map,curation]=await Promise.all(["../output/system-map.json","../curation/system-map-curation.json"].map(u=>fetch(u).then(r=>{if(!r.ok)throw Error(`${u}: ${r.status}`);return r.json()})));S.map=map;S.curation=curation;[...map.nodes,...curation.semanticNodes].forEach(n=>S.nodes.set(n.id,n));S.generated=map.edges;$("map-stats").textContent=`${map.nodes.length} generated nodes · ${map.edges.length} generated edges · v0.2 SVG renderer`;bindControls();showSystem()}catch(e){$("view-title").textContent="Map could not be loaded";$("view-summary").textContent=e.message}}
function node(id){return S.nodes.get(id)}function desc(n){return S.curation.descriptions[n.id]||n.description||({SQL:"MyBatis annotation SQL.",DB_OBJECT:"Database object referenced by SQL."}[n.type])||"Analyzer-generated structural fact."}function edgeEvidence(e){return e.evidence?.level||e.evidence||"STATIC"}function short(s,n=25){s=String(s);return s.length>n?s.slice(0,n-1)+"…":s}
function systemModel(){const ids=S.curation.systemView.nodeIds;return{kind:"system",label:"System",title:S.curation.system.label,summary:"Execution flows from left to right. Branches expose CSV input, orchestration, transaction processing, persistence, and database boundaries.",nodes:ids.map((id,i)=>({data:node(id),rank:null,order:i,semantic:id.startsWith("input:")||id.startsWith("database:")})),edges:S.curation.systemView.edges.map(e=>({...e,evidence:edgeEvidence(e)}))}}
function neighbors(id){return S.generated.filter(e=>e.from===id||e.to===id)}
function typeModel(n){const contained=S.generated.filter(e=>e.type==="CONTAINS"&&e.from===n.id);const incoming=S.generated.filter(e=>e.type==="CALL"&&e.to.startsWith(n.id+"#")).map(e=>e.from);const deps=S.generated.filter(e=>e.type==="DEPENDENCY"&&e.from===n.id);const ids=new Set([n.id,...incoming,...contained.map(e=>e.to),...deps.map(e=>e.to)]);let edges=[...contained,...deps,...S.generated.filter(e=>e.type==="CALL"&&ids.has(e.from)&&ids.has(e.to))];return{kind:"type",label:n.label,title:n.label,summary:"Callers enter from the left; contained methods and dependencies branch to the right.",nodes:[...ids].map((id,i)=>({data:node(id),rank:id===n.id?1:incoming.includes(id)?0:2,order:i})).filter(x=>x.data),edges}}
function methodModel(n){const incoming=S.generated.filter(e=>e.to===n.id);const outgoing=S.generated.filter(e=>e.from===n.id);const first=[...incoming,...outgoing];const sqlIds=outgoing.filter(e=>node(e.to)?.type==="SQL").map(e=>e.to);const second=S.generated.filter(e=>sqlIds.includes(e.from));const ids=new Set([n.id,...first.flatMap(e=>[e.from,e.to]),...second.map(e=>e.to)]);return{kind:"method",label:n.label,title:n.label,summary:"Focus + context: callers are left, the selected method is centered, and callees or SQL continue to database objects on the right.",nodes:[...ids].map((id,i)=>({data:node(id),rank:id===n.id?1:incoming.some(e=>e.from===id)?0:sqlIds.includes(id)?2:second.some(e=>e.to===id)?3:2,order:i})).filter(x=>x.data),edges:[...first,...second]}}
function leafModel(n){const es=neighbors(n.id);const ids=new Set([n.id,...es.flatMap(e=>[e.from,e.to])]);return{kind:n.type.toLowerCase(),label:n.label,title:n.label,summary:"The selected evidence remains connected to its immediate generated context.",nodes:[...ids].map((id,i)=>({data:node(id),rank:id===n.id?1:es.some(e=>e.to===n.id&&e.from===id)?0:2,order:i})).filter(x=>x.data),edges:es}}
function modelFor(n){return n.type==="TYPE"?typeModel(n):n.type==="METHOD"?methodModel(n):leafModel(n)}
function showSystem(){S.trail=[];S.selected=null;render(systemModel())}function openNode(id,push=true){const n=node(id);if(!n)return;if(push){if(!S.view||S.view.kind==="system")S.trail=[];S.trail.push({id:n.id,label:n.label})}S.selected=id;render(modelFor(n))}
function assignRanks(m){if(m.nodes.every(n=>n.rank!=null))return;const rank=new Map(m.nodes.map(n=>[n.data.id,0]));for(let k=0;k<m.nodes.length;k++)for(const e of m.edges)if(rank.has(e.from)&&rank.has(e.to))rank.set(e.to,Math.max(rank.get(e.to),rank.get(e.from)+1));m.nodes.forEach(n=>n.rank=rank.get(n.data.id)||0)}
function layout(m){assignRanks(m);const groups=new Map;for(const n of m.nodes){if(!groups.has(n.rank))groups.set(n.rank,[]);groups.get(n.rank).push(n)}const max=Math.max(...groups.keys(),0),W=Math.max(1100,(max+1)*285),positions=new Map;for(const [rank,items] of groups){items.sort((a,b)=>a.order-b.order);const gap=Math.max(155,650/(items.length+1));const total=(items.length-1)*gap;items.forEach((x,i)=>positions.set(x.data.id,{x:100+rank*(W-400)/Math.max(max,1),y:380-total/2+i*gap}))}return{positions,w:W,h:760}}
function render(m){S.view=m;$("view-kicker").textContent=`${m.kind.toUpperCase()} VIEW`;$("view-title").textContent=m.title;$("view-summary").textContent=m.summary;const L=layout(m),edgeLayer=$("edges"),nodeLayer=$("nodes");edgeLayer.innerHTML="";nodeLayer.innerHTML="";for(const e of m.edges){const a=L.positions.get(e.from),b=L.positions.get(e.to);if(!a||!b)continue;const x1=a.x+210,y1=a.y+43,x2=b.x,y2=b.y+43,dx=Math.max(55,(x2-x1)*.48);edgeLayer.insertAdjacentHTML("beforeend",`<path class="edge-path ${edgeEvidence(e)}" d="M${x1},${y1} C${x1+dx},${y1} ${x2-dx},${y2} ${x2},${y2}"/><text class="edge-label" x="${(x1+x2)/2}" y="${(y1+y2)/2-7}" text-anchor="middle">${esc(e.label||e.type)} · ${esc(edgeEvidence(e))}</text>`)}for(const item of m.nodes){const n=item.data,p=L.positions.get(n.id),selected=n.id===S.selected;nodeLayer.insertAdjacentHTML("beforeend",`<g class="graph-node ${selected?"selected":""} ${item.semantic?"semantic":""}" data-id="${esc(n.id)}" transform="translate(${p.x} ${p.y})" role="button" tabindex="0"><rect width="210" height="86"/><text class="node-kind" x="15" y="20">${esc(n.type)}</text><text class="node-label" x="15" y="44">${esc(short(n.label))}</text><text class="node-hint" x="15" y="66">${esc(selected?"SELECTED · double-click to expand":"click to focus")}</text></g>`)}document.querySelectorAll(".graph-node").forEach(g=>{g.onclick=()=>select(g.dataset.id);g.ondblclick=()=>openNode(g.dataset.id);g.onkeydown=e=>{if(e.key==="Enter")openNode(g.dataset.id)}});S.camera={x:0,y:0,w:L.w,h:L.h};applyCamera();renderCrumbs();renderDetail(S.selected?node(S.selected):null);$("parent").disabled=m.kind==="system"}
function select(id){S.selected=id;document.querySelectorAll(".graph-node").forEach(g=>g.classList.toggle("selected",g.dataset.id===id));renderDetail(node(id))}
function renderDetail(n){if(!n){$("detail").innerHTML=`<span class="eyebrow">START HERE</span><h3>${esc(S.curation.system.label)}</h3><p>${esc(S.curation.system.description)}</p><dl><dt>READING DIRECTION</dt><dd>Follow arrowheads from left to right.</dd><dt>INTERACTION</dt><dd>Click to inspect. Double-click to change semantic level.</dd></dl>`;return}const source=n.source?`${n.source.path}:${n.source.line}`:"Curated semantic node";const levels=[...new Set([...neighbors(n.id).map(edgeEvidence),...S.curation.systemView.edges.filter(e=>e.from===n.id||e.to===n.id).map(edgeEvidence)])];$("detail").innerHTML=`<span class="eyebrow">${esc(n.type)}</span><h3>${esc(n.label)}</h3><p>${esc(desc(n))}</p><dl><dt>SOURCE / PROVENANCE</dt><dd><code>${esc(source)}</code></dd><dt>EVIDENCE</dt><dd>${levels.length?levels.map(x=>`<span class="pill ${x}">${x}</span>`).join(""):"No edge evidence"}</dd>${n.details?.annotations?.length?`<dt>ANNOTATIONS</dt><dd>${n.details.annotations.map(a=>`<span class="pill">@${esc(a)}</span>`).join("")}</dd>`:""}${n.details?.statement?`<dt>SQL</dt><dd class="sql">${esc(n.details.statement)}</dd>`:""}</dl><button class="expand" data-expand="${esc(n.id)}">Expand semantic level</button>`;document.querySelector("[data-expand]").onclick=()=>openNode(n.id)}
function renderCrumbs(){const items=[{label:"System",id:null},...S.trail];$("breadcrumb").innerHTML=items.map((x,i)=>`${i?'<span class="crumb-sep">›</span> ':''}<button data-crumb="${i}">${esc(x.label)}</button>`).join("");document.querySelectorAll("[data-crumb]").forEach(b=>b.onclick=()=>{const i=+b.dataset.crumb;if(i===0)return showSystem();S.trail=S.trail.slice(0,i);openNode(S.trail[i-1].id,false)})}
function parent(){if(!S.trail.length)return showSystem();S.trail.pop();if(!S.trail.length)showSystem();else openNode(S.trail.at(-1).id,false)}function applyCamera(){$("graph").setAttribute("viewBox",`${S.camera.x} ${S.camera.y} ${S.camera.w} ${S.camera.h}`)}function zoom(f){const c=S.camera,nw=c.w*f,nh=c.h*f;c.x+=(c.w-nw)/2;c.y+=(c.h-nh)/2;c.w=nw;c.h=nh;applyCamera()}
function bindControls(){$("parent").onclick=parent;$("zoom-in").onclick=()=>zoom(.82);$("zoom-out").onclick=()=>zoom(1.22);$("fit").onclick=()=>render(S.view);const svg=$("graph");svg.onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?1.12:.89)};svg.onpointerdown=e=>{if(e.target.closest(".graph-node"))return;S.drag={x:e.clientX,y:e.clientY,c:{...S.camera}};svg.setPointerCapture(e.pointerId)};svg.onpointermove=e=>{if(!S.drag)return;const r=svg.getBoundingClientRect();S.camera.x=S.drag.c.x-(e.clientX-S.drag.x)*S.drag.c.w/r.width;S.camera.y=S.drag.c.y-(e.clientY-S.drag.y)*S.drag.c.h/r.height;applyCamera()};svg.onpointerup=()=>S.drag=null;const input=$("search"),results=$("search-results");input.oninput=()=>{const q=input.value.trim().toLowerCase();results.innerHTML=q?[...S.nodes.values()].filter(n=>n.label.toLowerCase().includes(q)).slice(0,9).map(n=>`<button class="result" data-result="${esc(n.id)}"><strong>${esc(n.label)}</strong> · ${esc(n.type)}</button>`).join(""):"";document.querySelectorAll("[data-result]").forEach(b=>b.onclick=()=>{openNode(b.dataset.result);input.value="";results.innerHTML=""})}}
document.addEventListener("DOMContentLoaded",init);
