const S={map:null,curation:null,nodes:new Map(),edges:[],objects:[],positions:new Map(),selected:null,selectedKind:null,camera:{x:0,y:0,w:1820,h:940},base:{w:1820,h:940},drag:null,pan:null};
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));const evidence=e=>e.evidence?.level||e.evidence||"STATIC";
const majorTypes=["type:io.github.kimchanj.etlperformance.etl.BaselineEtlRunner","type:io.github.kimchanj.etlperformance.etl.ShipmentImporter","type:io.github.kimchanj.etlperformance.etl.ShipmentCsvReader","type:io.github.kimchanj.etlperformance.etl.ShipmentTransactionService","type:io.github.kimchanj.etlperformance.persistence.EtlMapper"];
const initialPositions=[[35,345],[350,330],[675,55],[675,455],[1000,300],[1325,210],[1585,260]];
async function init(){try{const [map,curation]=await Promise.all(["../output/system-map.json","../curation/system-map-curation.json"].map(u=>fetch(u).then(r=>{if(!r.ok)throw Error(`${u}: ${r.status}`);return r.json()})));S.map=map;S.curation=curation;map.nodes.forEach(n=>S.nodes.set(n.id,n));curation.semanticNodes.forEach(n=>S.nodes.set(n.id,n));S.edges=map.edges;buildObjects();$("view-kicker").textContent="SYSTEM OBJECT MAP";$("view-title").textContent="CASE #01 ETL execution structure";$("view-summary").textContent="Classes expose method members; arrows connect the exact caller, callee, SQL, and database evidence.";bindControls();renderScene();resetSelection();$("map-stats").textContent=`${S.objects.length} visible knowledge objects · ${visibleEdges().length} evidence-backed relationships · 56 generated nodes`}catch(e){$("view-title").textContent="Map could not be loaded";$("view-summary").textContent=e.message}}
function buildObjects(){const contained=new Map;for(const e of S.edges.filter(e=>e.type==="CONTAINS")){if(!contained.has(e.from))contained.set(e.from,[]);contained.get(e.from).push(S.nodes.get(e.to))}const relevant=id=>S.edges.some(e=>(e.type==="CALL"||e.type==="MAPS_TO")&&(e.from===id||e.to===id));const types=majorTypes.map(id=>{const n=S.nodes.get(id),members=(contained.get(id)||[]).filter(m=>relevant(m.id)||n.label==="ShipmentCsvReader");return{id,n,kind:"TYPE",members}});const sql=S.map.nodes.filter(n=>n.type==="SQL"),dbIds=new Set(S.edges.filter(e=>e.type==="DB_ACCESS").map(e=>e.to)),db=S.map.nodes.filter(n=>dbIds.has(n.id));S.objects=[...types,{id:"object:mapper-sql",n:{id:"object:mapper-sql",label:"Mapper SQL",type:"SQL GROUP",description:"SQL statements declared by EtlMapper annotations."},kind:"SQL",members:sql},{id:"object:oracle",n:{id:"object:oracle",label:"Oracle / ETL_LAB",type:"DATABASE",description:"Database objects directly referenced by mapper SQL."},kind:"DATABASE",members:db}];S.objects.forEach((o,i)=>S.positions.set(o.id,{x:initialPositions[i][0],y:initialPositions[i][1]}))}
function ownerOf(id){return S.objects.find(o=>o.members.some(m=>m.id===id))}function endpointObject(id){return S.objects.find(o=>o.id===id)||ownerOf(id)}function visibleEdges(){return S.edges.filter(e=>["CALL","DEPENDENCY","MAPS_TO","DB_ACCESS"].includes(e.type)&&endpointObject(e.from)&&endpointObject(e.to))}function objectSize(o){return{w:270,h:48+o.members.length*30}}
function anchor(id,side){const direct=S.objects.find(o=>o.id===id),owner=direct||ownerOf(id);if(!owner)return null;const p=S.positions.get(owner.id),size=objectSize(owner);let y=p.y+24;if(!direct)y=p.y+48+owner.members.findIndex(m=>m.id===id)*30+15;return{x:p.x+(side==="out"?size.w:0),y}}
function short(s){return s.length>30?s.slice(0,29)+"…":s}
function renderScene(){const nodes=$("nodes");nodes.innerHTML="";for(const o of S.objects){const p=S.positions.get(o.id),z=objectSize(o),selected=S.selectedKind==="object"&&S.selected===o.id;nodes.insertAdjacentHTML("beforeend",`<g class="knowledge-object ${selected?"selected":""}" data-object="${esc(o.id)}" transform="translate(${p.x} ${p.y})"><rect class="object-shell" width="${z.w}" height="${z.h}"/><g class="object-header" data-drag="${esc(o.id)}"><rect width="${z.w}" height="48"/><text class="object-kind" x="14" y="16">${esc(o.n.type)}</text><text class="object-title" x="14" y="36">${esc(o.n.label)}</text><text class="drag-hint" x="${z.w-13}" y="29" text-anchor="end">⠿</text></g>${o.members.map((m,i)=>`<g class="member-row ${S.selectedKind==="member"&&S.selected===m.id?"selected":""}" data-member="${esc(m.id)}" transform="translate(0 ${48+i*30})"><rect width="${z.w}" height="30"/><circle class="member-dot" cx="0" cy="15" r="4"/><circle class="member-dot" cx="${z.w}" cy="15" r="4"/><text class="member-type" x="13" y="19">${m.type==="METHOD"?"M":m.type==="SQL"?"SQL":"DB"}</text><text class="member-text" x="45" y="19">${esc(short(m.label))}</text></g>`).join("")}</g>`)}renderPaths();bindObjectEvents();applyCamera();updateSemantic();renderBreadcrumb()}
function renderPaths(){const layer=$("edges"),activeEdges=connectedEdges();layer.innerHTML="";for(const e of visibleEdges()){const a=anchor(e.from,"out"),b=anchor(e.to,"in");if(!a||!b)continue;const dx=Math.max(42,Math.abs(b.x-a.x)*.42),active=!S.selected||activeEdges.includes(e),dim=S.selected&&!active,d=`M${a.x},${a.y} C${a.x+dx},${a.y} ${b.x-dx},${b.y} ${b.x},${b.y}`;layer.insertAdjacentHTML("beforeend",`<g class="relation ${active?"active":""} ${dim?"dim":""}"><path class="edge-path ${esc(e.type)} ${esc(evidence(e))}" d="${d}"/><text class="edge-label ${S.selected&&active?"show":""}" x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2-6}" text-anchor="middle">${esc(e.type)} · ${esc(evidence(e))}</text></g>`)}}
function connectedEdges(){if(!S.selected)return[];if(S.selectedKind==="member")return visibleEdges().filter(e=>e.from===S.selected||e.to===S.selected);const o=S.objects.find(x=>x.id===S.selected),ids=new Set([o?.id,...(o?.members||[]).map(m=>m.id)]);return visibleEdges().filter(e=>ids.has(e.from)||ids.has(e.to))}
function connectedObjects(){const set=new Set;if(!S.selected)return set;for(const e of connectedEdges()){const a=endpointObject(e.from),b=endpointObject(e.to);if(a)set.add(a.id);if(b)set.add(b.id)}return set}
function refreshSelection(){const related=connectedObjects();document.querySelectorAll(".knowledge-object").forEach(g=>g.classList.toggle("dim",S.selected&&!related.has(g.dataset.object)&&g.dataset.object!==S.selected));document.querySelectorAll(".member-row").forEach(g=>g.classList.toggle("selected",S.selectedKind==="member"&&g.dataset.member===S.selected));renderPaths()}
function selectObject(id){S.selected=id;S.selectedKind="object";refreshSelection();renderDetail(S.objects.find(o=>o.id===id));renderBreadcrumb()}function selectMember(id){S.selected=id;S.selectedKind="member";refreshSelection();renderMemberDetail(S.nodes.get(id));renderBreadcrumb()}
function description(n){return S.curation.descriptions[n.id]||n.description||({METHOD:"Analyzer-generated method.",SQL:"MyBatis annotation SQL.",DB_OBJECT:"Database object directly referenced by SQL."}[n.type])||"Structured knowledge object."}function evidenceLevels(id){return[...new Set(S.edges.filter(e=>e.from===id||e.to===id).map(evidence))]}
function renderDetail(o){const source=o.n.source?`${o.n.source.path}:${o.n.source.line}`:"Composite view object";$("detail").innerHTML=`<span class="eyebrow">KNOWLEDGE OBJECT · ${o.kind}</span><h3>${esc(o.n.label)}</h3><p>${esc(description(o.n))}</p><dl><dt>MEMBERS</dt><dd>${o.members.length} visible members</dd><dt>CONNECTED RELATIONSHIPS</dt><dd>${connectedEdges().length}</dd><dt>SOURCE / PROVENANCE</dt><dd><code>${esc(source)}</code></dd></dl><p class="detail-help">Select a member row to isolate its callers, callees, SQL, or database evidence.</p>`}
function renderMemberDetail(n){const es=connectedEdges(),source=n.source?`${n.source.path}:${n.source.line}`:"Generated database object";$("detail").innerHTML=`<span class="eyebrow">MEMBER · ${esc(n.type)}</span><h3>${esc(n.label)}</h3><p>${esc(description(n))}</p><dl><dt>SOURCE / PROVENANCE</dt><dd><code>${esc(source)}</code></dd><dt>RELATIONSHIPS</dt><dd>${es.map(e=>`<span class="pill">${esc(e.type)} → ${esc(S.nodes.get(e.to)?.label||e.to)}</span>`).join("")||"No visible relationship"}</dd><dt>EVIDENCE</dt><dd>${evidenceLevels(n.id).map(x=>`<span class="pill ${x}">${x}</span>`).join("")||"No edge evidence"}</dd>${n.details?.annotations?.length?`<dt>ANNOTATIONS</dt><dd>${n.details.annotations.map(a=>`<span class="pill">@${esc(a)}</span>`).join("")}</dd>`:""}${n.details?.statement?`<dt>SQL</dt><dd class="sql">${esc(n.details.statement)}</dd>`:""}</dl>`}
function renderBreadcrumb(){const item=S.selectedKind==="member"?S.nodes.get(S.selected)?.label:S.objects.find(o=>o.id===S.selected)?.n.label;$("breadcrumb").innerHTML=`<button data-home>System Object Map</button>${item?`<span class="crumb-sep">›</span><button>${esc(item)}</button>`:""}`;document.querySelector("[data-home]").onclick=resetSelection}
function resetSelection(){S.selected=null;S.selectedKind=null;document.querySelectorAll(".dim,.selected").forEach(x=>x.classList.remove("dim","selected"));renderPaths();$("detail").innerHTML=`<span class="eyebrow">ER-STYLE SOURCE MAP</span><h3>Knowledge Object → Members → Relationships</h3><p>Class objects expose method rows. Evidence-backed edges connect the exact members involved.</p>`;renderBreadcrumb()}
function applyCamera(){$("graph").setAttribute("viewBox",`${S.camera.x} ${S.camera.y} ${S.camera.w} ${S.camera.h}`)}function updateSemantic(){const scale=S.base.w/S.camera.w,level=scale<.72?"overview":scale>1.35?"detail":"normal";$("graph").dataset.semantic=level;$("semantic-level").textContent=level.toUpperCase()}function zoom(f){const c=S.camera,nw=c.w*f,nh=c.h*f;c.x+=(c.w-nw)/2;c.y+=(c.h-nh)/2;c.w=nw;c.h=nh;applyCamera();updateSemantic()}
function resetLayout(){S.objects.forEach((o,i)=>S.positions.set(o.id,{x:initialPositions[i][0],y:initialPositions[i][1]}));S.camera={x:0,y:0,...S.base};renderScene()}function clientToSvg(e){const r=$("graph").getBoundingClientRect();return{x:S.camera.x+(e.clientX-r.left)*S.camera.w/r.width,y:S.camera.y+(e.clientY-r.top)*S.camera.h/r.height}}
function bindObjectEvents(){document.querySelectorAll("[data-object]").forEach(g=>g.onclick=e=>{if(!e.target.closest(".member-row"))selectObject(g.dataset.object)});document.querySelectorAll("[data-member]").forEach(g=>g.onclick=e=>{e.stopPropagation();selectMember(g.dataset.member)});document.querySelectorAll("[data-drag]").forEach(h=>h.onpointerdown=e=>{e.stopPropagation();const id=h.dataset.drag,p=clientToSvg(e),at=S.positions.get(id);S.drag={id,dx:p.x-at.x,dy:p.y-at.y};$("graph").setPointerCapture(e.pointerId)})}
function bindControls(){$("parent").onclick=resetSelection;$("zoom-in").onclick=()=>zoom(.82);$("zoom-out").onclick=()=>zoom(1.22);$("fit").onclick=()=>{S.camera={x:0,y:0,...S.base};applyCamera();updateSemantic()};$("reset-layout").onclick=resetLayout;const svg=$("graph");svg.onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?1.12:.89)};svg.onpointerdown=e=>{if(e.target.closest(".knowledge-object"))return;const p=clientToSvg(e);S.pan={x:p.x,y:p.y,c:{...S.camera}};svg.setPointerCapture(e.pointerId)};svg.onpointermove=e=>{const p=clientToSvg(e);if(S.drag){S.positions.set(S.drag.id,{x:p.x-S.drag.dx,y:p.y-S.drag.dy});const g=document.querySelector(`[data-object="${CSS.escape(S.drag.id)}"]`),at=S.positions.get(S.drag.id);g.setAttribute("transform",`translate(${at.x} ${at.y})`);renderPaths();return}if(S.pan){S.camera.x=S.pan.c.x-(p.x-S.pan.x);S.camera.y=S.pan.c.y-(p.y-S.pan.y);applyCamera()}};svg.onpointerup=()=>{S.drag=null;S.pan=null};const input=$("search"),results=$("search-results");input.oninput=()=>{const q=input.value.trim().toLowerCase(),items=[...S.objects.map(o=>o.n),...S.map.nodes].filter(n=>n.label.toLowerCase().includes(q)).slice(0,10);results.innerHTML=q?items.map(n=>`<button class="result" data-result="${esc(n.id)}"><strong>${esc(n.label)}</strong> · ${esc(n.type)}</button>`).join(""):"";document.querySelectorAll("[data-result]").forEach(b=>b.onclick=()=>{const o=S.objects.find(o=>o.id===b.dataset.result);o?selectObject(o.id):selectMember(b.dataset.result);input.value="";results.innerHTML=""})}}
document.addEventListener("DOMContentLoaded",init);
